### ISSUE TITLE
Feature: User can signup/login/out

### ISSUE THREAD

**Issue by EvanS-Hong** [EvanS-Hong/Final-Project#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can… signup/Log in/logout 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to signup/login/logout of the website

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/121647785/232605393-f4a3cf5d-c2e6-46a3-86b4-1ac6cf5c0391.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Create DataBase with 2 tables: User and Location
- [x] Create `schema.sql` to accept user input for username & password(hashed) and store it into the database for later user.

### ☁️ Server Tasks

- [x] Create react app.

### ⚡ Client Tasks

- [x] Create component to render main page
  - [x] Create component login button and main page that requires login before moving forward
  - [x] Create Dummy component for Drawer
  - [x] Create CSS for page out (mobile for now)
 

### 🧑‍⚕️ Clean Up Tasks

- [x] Ensure signup doesn't allow for duplicate usernames
- [x] Make sure passwords are store ONLY in hash and that you can login/logout
- [x] User stays logged in even on page refresh
- [x] Cleanup any unnecessary CSS
