### ISSUE TITLE
Feature: User can  view a location via google maps

### ISSUE THREAD

**Issue by EvanS-Hong** [EvanS-Hong/Final-Project#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view a location via google maps

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to enter an address/Coordinates and get a view of the location and its surrounding area

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/121647785/232606640-addbfa90-8a96-4489-b5b4-521ea2f291b7.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] call to google maps static api to render map
- [x] call geocoding api to get latitude and longitude of location
- [x] Create a component to render the map
- [x] create drawer  component for menu/lists

### 🧑‍⚕️ Clean Up Tasks

- [x] clean up code
- [x] text/fix any bugs
