### ISSUE TITLE
Feature: User can add/pin the location

### ISSUE THREAD

**Issue by EvanS-Hong** [EvanS-Hong/Final-Project#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?
User can add/pin the location
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.
User will be able to save the looked at location in a list for future use./

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/121647785/232606081-2b885da2-5423-4c27-a935-8e2ef343a8a3.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### ☁️ Server Tasks

- [x] Add post request to server to add location data

### ⚡ Client Tasks

- [x] Add a route to the main page to connect the link to the component
- [x] Create a component to allow users to find a location and fill out details
- [x] connect the component to the server side

### 🧑‍⚕️ Clean Up Tasks

- [x] Check for bugs
- [x] add CSS for cleaner appearance
- [x] cleanup any loose code/ delete any debugging code
