### ISSUE TITLE
Feature: User can view locations/pins on based off regions/prefectures

### ISSUE THREAD

**Issue by EvanS-Hong** [EvanS-Hong/Final-Project#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can…view locations/pins on based off regions/prefectures

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When user opens the drawer they will be able to select saved locations based off the regions/country they were saved under.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/121647785/232606295-392805fa-6c84-4dee-8c22-80f2ae0177bd.png)

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...

### ☁️ Server Tasks

- [x] Update `server.js` to ...
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client Tasks

- [x] Create a component to ...
- [x] Update component to ...

### 🧑‍⚕️ Clean Up Tasks

- [ ] ... 
- [ ] ...
- [x] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
- [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
